version: '3.8'
services:
  asana-notification:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: python asana-notification-web.py
