version: '3.8'
services:
  asana-notification:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: python asana-notification.py --max-projects 5
    env_file:
      - .env
